--Total customers by country
select country, COUNT(customer_key) as total_customers 
from gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;


--Total customers by gender
select gender, COUNT(customer_key) as total_customers 
from gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;


--Total products by category
select category, COUNT(product_key) as total_products
from gold.dim_products
GROUP BY category
ORDER BY total_products DESC;


--Avg costs in each category
select category, AVG(cost) as avg_cost
from gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC;


--Total revenue generated for each category
select dp.category, SUM(fs.sales_amount) as total_revenue from gold.dim_products dp
LEFT JOIN gold.fact_sales fs
ON dp.product_key = fs.product_key
GROUP BY dp.category
ORDER BY total_revenue DESC;

--Revenue generated by each customer
select dc.customer_key, dc.first_name, dc.last_name, SUM(fs.sales_amount) as revenue_generated from gold.dim_customers dc
LEFT JOIN gold.fact_sales fs
ON dc.customer_key = fs.customer_key
GROUP BY dc.customer_key, dc.first_name, dc.last_name
ORDER BY revenue_generated DESC;


--Distribution of sold items across countries
select dc.country, SUM(fs.quantity) AS sold_items from gold.dim_customers dc
LEFT JOIN gold.fact_sales fs
ON dc.customer_key = fs.customer_key
GROUP BY dc.country
ORDER BY sold_items DESC;
